claudiodangelis/qrcp

main.go
Instead of using freeport.GetFreePort() this PR creates a net.Listener bound to the chosen ip address and gets a system chosen available port.  The net.Listner is passed to http.Serve which is used instead of http.ListenAndServe. This eliminates issues because of differing values for localhost across systems, a port not being used on the address localhost maps to but on the choosen address and the potential for a port being used in the time between the check it is available and actually binding to it. Issue #3 should be resolved by this PR.
=> Remove freeport. Use a net.Listener and http.Serve

util.go
Filters down interfaces out of the list presented for possible use.
=> Filter out down interfaces

config.go
concating strings with "+" for PATH is not good manners.
=> use path/filepath

README.md, main.go, util.go
=> Add -quiet flag to suppress non critical output

main.go
Also characters using are not displayed correctly.
See https://github.com/claudiodangelis/qr-filetransfer/pull/49
=> Windows does not handle escape sequence

util.go
solved the `to do` to change 3 `ifs` for a `regex`.
=> add regex to get the address

main.go, serveHTTP.go
Just pulled all serving logic out of the main function.
=> refactor main.go

content.go
More info: https://github.com/claudiodangelis/qr-filetransfer/issues/70
=> fix issue #70

serveHTTP.go, util.go
feature request: https://github.com/claudiodangelis/qr-filetransfer/issues/71
=> add output of payload's size in human-readable format

serveHTTP.go
- Use MultipartReader instead of ParseMultipartForm
- Add progress bar to indicate transfer progress
This should resolve #67
=> Make mobile-to-desktop transfer more verbose

README.md
BTW, thanks for this awesome tool :)
=> Fix link to the source package on AUR

pages/pages.go
As specified on #88.
I did it using javascript with ajax on the client side to keep the server code uniform.
=> Add receive plain text feature

go.mod, go.sum, qr/qr.go
Changed qr-code library to `github.com/skip2/go-qrcode` ,  which is updated more frequently with quite a lot of other features as-well. 
- Particularly, generating PNG files on the fly, which might be useful down the line for further enhancement of qrcp.
=> ADDED NEW QRcode LIBRARY

README.md
=> Update pearl2201/qrcp description in README.md

README.md
Hi, Claudio --
I've had qrcp merged into the main bucket of the scoop installer project (scoop.sh).
Cheers!
=> Add alternative Windows installation method

README.md, config/config.go
Hello @j0hax, I created a new PR with some refactoring here.
Thanks again for your headsup on this.
=> Set port through env var

README.md
Hi @qrcp_devs,
I have created this Pull Request because I have resolved this [request for a Chocolatey package](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1077) and now, we can install **qrcp** using [Chocolatey](https://community.chocolatey.org/packages/qrcp).
For now, only the latest version (`0.9.1`) is available on Chocolatey. When new versions will be released, they will, then, be added to the Chocolatey package for users to enjoy. :slightly_smiling_face:
=>  Adds the Chocolatey package as a way to install Qrcp

server/server.go, util/net.go
I fixed some typos that I found with [`typos`](https://github.com/crate-ci/typos).
=> Fixed typos

cmd/completion.go, cmd/send.go, config/config_test.go, config/migrate.go, util/util.go
* Remove deprecated ioutil package
* Remove deprecated cobra.ExactValidArgs
* Remove unreachable codepath
=> Minor cleanup

util/util.go
Fix slice initialization error
=> Fix slice initialization error

config/config.go
=> feat(config): don't panic on non-writeable file

.goreleaser.yml
This PR adds the additional zip format for Windows releases.
This is related to #352
=> chore(ci): add zip archive format for win
