claudiodangelis/qrcp

main.go

A request does not carry Content-Type information in its headers, just leave it unset, and http.ServeFile will set it automatically.

fix Content-Type header in http response

---

util.go

This PR changes findIP to skip any link local ip addresses and to properly return IPv6 addresses enclosed within brackets. This will add support for IPv6 while also preventing the binding errors which occur for many people on macos.

Check for link local address and support IPv6

---

util.go

Do not ask for candidate IP, when filtered IPs only have one option. References issue https://github.com/claudiodangelis/qr-filetransfer/issues/43 .

util.go : getAddress() choose default client automatically

---

util.go

It is possible that the filtered interface list could end up being empty. PR changes getAddress to return an error in this case.

Return an error when no interfaces are available

---

README.md
main.go

Added `-reverse` for make is suitable for terminals with a lighter background and darker foreground.
Wishlist item #12

Added a flag for reversing the QR code color

---

README.md

Thought your project was pretty neat. Decided to write a node.js clone/fork and wondered if you'd like to reference my project?
Totally cool if you don't want to.

Add reference to node.js clone, "quick-transfer".

---

LICENSE.GO
main.go
tcpKeepAliveListener.go
util.go

Supports parallel downloads while still having the application close when the download is complete. It accomplishes this by creating a sync.WaitGroup which the handler adds and decrements. When it reaches zero, all requests have been serviced, it shuts the server down, removes deletable files, updates the config and exits. To ensure that only a single transfer can occur it creates and attaches a session cookie which is checked for upon each request. Any request after the initial one without the cookie receives a 404 status.
It also tries to deal with the issue of barcode apps causing premature closure. For the first request it checks if the User-Agent begins with "Mozilla" which basically all mobile and desktop browser agent strings do. If it doesn't a 200 status is returned and the …

Add support for parallel downloads

---

main.go
serveHTTP.go

More info: https://github.com/claudiodangelis/qr-filetransfer/issues/58

add receive feature

---

cmd/receive.go
server/server.go

where receive dir is not exist
`
qrcp receive --output=/abcd/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1410e68]
goroutine 1 [running]:
github.com/claudiodangelis/qrcp/server.(*Server).ReceiveTo(0xc00028c000, 0x7ffeefbffb5e, 0x6, 0x0, 0x0)
/Users/heyong/gomod-workspace/my-qrcp/server/server.go:45 +0x78
github.com/claudiodangelis/qrcp/cmd.receiveCmdFunc(0x18ea6a0, 0xc000068290, 0x0, 0x1, 0x0, 0x0)
/Users/heyong/gomod-workspace/my-qrcp/cmd/receive.go:24 +0x1c9
github.com/spf13/cobra.(*Command).execute(0x18ea6a0, 0xc000068280, 0x1, 0x1, 0x18ea6a0, 0xc000068280)
/Users/heyong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x18ea400, …

Check if output dir not exists

---

config/config.go

Change port to be parsed as uint16 instead of int16 to allow for full range of valid ports.

Fix bug where config interface wouldn't allow port > 32767

---

README.md
cmd/qrcp.go
cmd/receive.go
cmd/send.go
config/config.go
server/server.go
util/util.go

This PR brings the support for HTTPS. Specifications:
EDIT:
I removed the following item from the specs, because I don't really feel the need of it:
_- default cert and key can be stored to a configurable directory which defaults to `$HOME/.qrcp/tls`_

Add support for HTTPS

---

README.md

Updating readme to advertise the inclusion of `qrcp` in Homebrew core tap (https://github.com/Homebrew/homebrew-core/pull/54368 by @zub, in response to #112) 🎉

Add Homebrew installation method to the readme

---

server/server.go

Related to: #223 
This was apparently an issue on the `mime/multipart` package of Go itself, which has been fixed 10 months ago, a few weeks after the latest release of qrcp.
Links:
- https://go-review.googlesource.com/c/go/+/313809
- https://github.com/golang/go/commit/784ef4c53135644d70f3476a4bd90010b9acff66

Extract base from multipart

---

config/config.go

Gives users the option to set the port through a `QRCP_PORT` environment variable. Allows for easier scripting and usage with firewalls. `QRCP_PORT` is only used if there is no flag or configuration specified (lowest priority) which allows for flexibility even when the environment variable has been set, for example, in a shell profile.
```console
$ QRCP_PORT=42069 ./qrcp main.go
Scan the following URL with a QR reader to start the file transfer, press CTRL+C or "q" to exit:
http://192.168.1.131:42069/send/7v6k
```
```console
$ QRCP_PORT=42069 ./qrcp main.go -p 65511
Scan the following URL with a QR reader to start the file transfer, press CTRL+C or "q" to exit:
http://192.168.1.131:65511/send/8qca
```
```console
$ QRCP_PORT=hello ./qrcp main.go
Error: could not parse port from environment …
```

Allow for setting port through environment variable

---

README.md

Starting Go 1.18, go get no longer builds packages.  go install must be used to install a module.

Updated instructions to install development version

---

README.md
application/application.go
cmd/qrcp.go
config/config.go
config/config_test.go
config/testdata/full.yml
server/server.go

This PR adds the `bind` configuration parameter to set the bind address to listen to.
The `bind` parameter overrides the address of the `interface` parameter.
Configuration file:
```yaml
bind: 10.20.30.40
```
Command line:
```sh
qrcp --bind 10.20.30.40 /some/file
```
To get more context about this feature, refer to the issue: #264 .

Implement bind argument

---

pages/pages.go

`:` is not allowed in windows filename

Fix default text filename not valid on windows

---

application/application.go
go.mod
go.sum
util/util.go

This could fix the issue with the incorrect zip files (#317) and the delete of the temporary zip files in Windows (#277).
To fix the incorrect zip compression i reuse the archivex library (like it  was done at the beginning) but for fixing the delete of the temporary zip files in Windows, i use the "CreateWriter" function in order to close, at the end of function, the writer and the file.

Fixing deleting temp files and incorrect zip file

---

server/server.go

Fixes #331
Relates-to: #253
Before:
```
Content-Disposition: "attachment; filename=\xe5\x95\x8a.txt"
```
After:
```
Content-Disposition: "attachment; filename=\"\xe5\x95\x8a.txt\"; filename*=UTF-8''%E5%95%8A.txt"
```

fix: Add UTF-8 filename* in Content-Disposition

---

config/config.go

fix(config): correct https-related fields in wizard

---

server/server.go

The external IP module can return an IPv6 address, in which case the method to append a port is to wrap it in square brackets before appending the `:%d` port string.
Unfortunately Go's IP module does not have a great way to determine whether an address is an IPv6 address, so fall back to counting the number of colons in the result as suggested in https://stackoverflow.com/a/48519490.

Fix link when external IP is IPv6

---

README.md

I love the idea of QRCP, so I built an Android app that allows the same method of sharing -- between phones.

Add new Android "clone" project to README.md

---

docs/tutorials/secure-transfers-with-mkcert.md

Found via `codespell -H -L iif`

docs: fix typo

---

.goreleaser.yml

links in the github release download link table were 404ing

Fix release download link table
